baseURL = "https://sffbook.club"

# This is a "one page"-website, so we do not need these kinds of pages...
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT", "404"]

defaultContentLanguage = "en"

# The name of this wonderful theme ;-).
theme = "hugo-product-launch"

# The "title" of your website
title = "Pittsburgh Sci-fi & Fantasy Book Club"

# Render line-breaks in .md-files as line-breaks in HTML.
# This is e.g. useful for rendering a multi-line address.
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
hardWraps = true

[params]
# A "copyright"-line to be added at the bottom of the page.
# Hint: Markdown is supported in here as well. So you may e.g. add a link to your legal imprint-page.
copyright = ""

# The "description" of your website. This is used in the meta data of your generated html.
description = "Pittsburgh Sci-fi & Fantasy Book Club"

# The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
# Hint: It's good practise to also put a "favicon.ico"-file into your "static"-folder.
favicon = "images/favicon.png"

# These "images" are used for the structured data templates. This will show up, when
# services like Twitter or Slack want to generate a preview of a link to your site.
# See https://gohugo.io/templates/internal#twitter-cards and
# https://gohugo.io/templates/internal#open-graph.
images = ["images/share-image.png"]

# Another "title" :-). This one is used as the site_name on the Hugo's internal
# opengraph structured data template.
# See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
title = "Pittsburgh Sci-fi & Fantasy Book Club"

# LICENSE: Hugo Product Launch by Jan Raasch is licensed
# under Attribution 4.0 International (CC BY 4.0).
# See https://github.com/janraasch/hugo-product-launch#license.
# This theme will, by default, inject a design-by-line at the bottom of the page.
# **If** you would like to use this theme without attribution,
# permissions beyond this license's scope **are available** at
# https://github.com/janraasch/hugo-product-launch/blob/master/MORE_PERMISSIONS.md
# hidedesignbyline = true

[params.meta]
keywords = "some, keywords, for, seo, you, know, google, duckduckgo, and, such"

# Tailwind CSS build configuration for Hugo.
# See https://gohugo.io/functions/css/tailwindcss.
[build]
writeStats = true
[[build.cachebusters]]
source = "assets/watching/hugo_stats\\.json"
target = "styles\\.css"
[[build.cachebusters]]
source = "(postcss|tailwind)\\.config\\.js"
target = "css"
[[build.cachebusters]]
source = "assets/.*\\.(js|ts|jsx|tsx)"
target = "js"
[[build.cachebusters]]
target = "$1"

[caches]
[caches.images]
dir = ':cacheDir/images'

[module]
[module.hugoVersion]
extended = false
min = "0.112.0"
[[module.mounts]]
source = "assets"
target = "assets"
[[module.mounts]]
source = "hugo_stats.json"
target = "assets/watching/hugo_stats.json"
